add the "-s" & "-l" parameters to  perfcharts 	modified:   cgt-perf 	new file:   cgt-timestamp

diff --git a/src/chartgeneration-perftest/bin/cgt-perf b/src/chartgeneration-perftest/bin/cgt-perf
--- a/src/chartgeneration-perftest/bin/cgt-perf
+++ b/src/chartgeneration-perftest/bin/cgt-perf
@@ -18,6 +18,8 @@ show_usage() {
 	echo "	-f FROM_TIME	specify the start time of duration, like '2014-12-18 9:30:00'"
 	echo "	-t TO_TIME	specify the end time of duration, like '2014-12-18 17:30:00'"
 	echo "	-e EXCLUSION_PATTERN	specify the pattern (regular expression) which is used to exclude some transactions for average TPS & RT  calculation, like 'ping\.html'"
+	echo "	-s START_OFFSET specify the 'Ramp-up Period' of [Loading] testing. Perfcharts will ignore the test results in the period"
+	echo "	-l TEST_DURATION specify the last time of [Loading] testing. Perfcharts will anaylze the test results from 'START_OFFSET'+'START_OFFSET'+'TEST_DURATION'"
 }
 
 # initialize global variables
@@ -27,7 +29,7 @@ if ! [ -n "$CGT_LOG" ]; then export CGT_LOG=$CGT_HOME/log; fi
 if ! [ -n "$CGT_JAVA_COMMAND" ]; then export CGT_JAVA_COMMAND=java; fi
 input_dir=\.
 # deal with arguments
-while getopts d:o:z:f:t:e:? opt; do
+while getopts d:o:z:f:t:e:s:l:? opt; do
 	case $opt in
 	d) 
 		output_dir=$OPTARG;;
@@ -41,6 +43,10 @@ while getopts d:o:z:f:t:e:? opt; do
 		end_time=$OPTARG;;
 	e)
 		exclusion_pattern=$OPTARG;;
+	s) 
+		start_offset=$OPTARG;;
+	l)
+		test_duration=$OPTARG;;
 	?|*)	echo
 		show_usage
 		exit -1;;
@@ -57,6 +63,8 @@ if ! [ -n "$report_file" ]; then report_file=$output_dir/report.html; fi
 bin_dir=$CGT_HOME/bin
 cgt_js=$bin_dir/cgt-js
 cgt_monoreport=$bin_dir/cgt-monoreport
+#Add for cgt_timestamp
+cgt_timestamp=$bin_dir/cgt-timestamp
 perftest_parser=$CGT_LIB/chartgeneration-perftest-parser.jar
 perftest_generator=$CGT_LIB/chartgeneration-core.jar
 jmeter_default_config_file=$CGT_HOME/res/jmeter.chartconf
@@ -73,6 +81,22 @@ jmeter_json_file=$json_dir/Performance.json
 # parse raw data to data tables
 echo "remove tmp directory '$tmp_dir'" >&2
 rm "$tmp_dir" -Rf
+# check the start_offset and get the smallestts
+if [ -n "$start_offset" ] && [ -n "$test_duration" ] && [ !-n "$start_time"] ; then
+	smallestts=$($cgt_timestamp "$input_dir")
+	start_time_str=$(expr "$smallestts" + "$start_offset")
+	start_time=$(expr $start_time_str / 1000)
+	start_time=$(date -u -d @${start_time} +'%Y-%m-%d %H:%M:%S')
+	echo $start_time
+	end_time_str=$(expr "$start_time_str" + "$test_duration")
+	end_time_str=$(expr $end_time_str / 1000)
+	end_time=$(date -u -d @${end_time_str} +'%Y-%m-%d %H:%M:%S')
+	echo $end_time
+elif [ -n "$start_time" ]; then
+	echo "[Error] '-s' can not be used with '-f'"
+	exit
+fi
+
 for file in "$input_dir"/*; do
 if [ -f "$file" ]; then
 	echo "parsing input file '$file'..." >&2
@@ -91,15 +115,17 @@ if [ -f "$file" ]; then
 		elif [ "$file_extension" == "zabbix" ]; then
 			parser_class=ZabbixParser
 		fi
-		#echo $CGT_JAVA_COMMAND "-DstartTime=$start_time" "-DendTime=$end_time" -jar "$perftest_parser" "$parser_class" "$time_zone" \< "$file" \>\> "$resource_monitoring_dir/$server_name.csv"
-		if ! $CGT_JAVA_COMMAND "-DstartTime=$start_time" "-DendTime=$end_time" -jar "$perftest_parser" "$parser_class" "$time_zone" < "$file" >> "$resource_monitoring_dir/$server_name.csv"; then
+		if ! $CGT_JAVA_COMMAND  "-DstartTime=$start_time" "-DendTime=$end_time" -jar "$perftest_parser" "$parser_class" "$time_zone"  < "$file" >> "$resource_monitoring_dir/$server_name.csv"; then
+                        exit 1
+                fi
+		if ! $CGT_JAVA_COMMAND "-DstartTime=$start_time" "-DendTime=$end_time" -jar "$perftest_parser" "$parser_class" "$time_zone"  < "$file" >> "$resource_monitoring_dir/$server_name.csv"; then
 			exit 1
 		fi
 		;;
-	jtl)
+	jtl|csv)
 		mkdir -p "$jmeter_dir"
 		parser_class=JmeterParser
-		if ! $CGT_JAVA_COMMAND "-DstartTime=$start_time" "-DendTime=$end_time" -jar "$perftest_parser" "$parser_class" "$time_zone" < "$file" >> "$jmeter_data_table"; then
+		if ! $CGT_JAVA_COMMAND "-DstartTime=$start_time" "-DendTime=$end_time" -jar "$perftest_parser" "$parser_class" "$time_zone"< "$file" >> "$jmeter_data_table"; then
 			exit 1
 		fi
 		;;
@@ -121,7 +147,7 @@ if [ -f "$jmeter_data_table" ]; then
 	encoded_exclusion_pattern=${exclusion_pattern//\\/\\\\}
 	encoded_exclusion_pattern=${encoded_exclusion_pattern////\\\/}
 	sed "s/<!--{command_line_exclusion_pattern}-->/${encoded_exclusion_pattern}/g" "$config_file_template" > "$jmeter_dir/jmeter.chartconf"
-	if ! $CGT_JAVA_COMMAND -jar "$perftest_generator" "$jmeter_dir/jmeter.chartconf" < "$jmeter_data_table" > "$jmeter_json_file"; then
+	if ! $CGT_JAVA_COMMAND -Xms2048m -Xmx2048m -jar "$perftest_generator" "$jmeter_dir/jmeter.chartconf" < "$jmeter_data_table" > "$jmeter_json_file"; then
 		exit 1
 	fi
 fi
